### ISSUE TITLE
Why the wide search tolerance?

### ISSUE THREAD

**Issue by andrewjmc** [guo-xuan/Sipros-Ensemble#2]
Hello,

I'm interested to understand why the parent mass tolerance is encouraged to be so wide even for high resolution scans? What benefit is obtained by considering peptides which are well outside the parent mass tolerance window? I assume it significantly increases the number of theoretical spectra which have to be considered, and therefore increases the run time?

```
# Parent mass tolerance for database searching
# Recommend 1 Da for both High-res MS2 and Low-res MS2 to improve identification results
# Peptides with large errors for parent ions can be filtered out using the parameter Filter_Mass_Tolerance_Parent_Ion
Search_Mass_Tolerance_Parent_Ion = 1
```

Thanks for your help,

Andrew

**Comment by guo-xuan** [comment]
Hi Andrew,

Thank you for your interest in Sipros Ensemble.
Sipros uses a large parent mass tolerance in the database search, and reduce the parent mass tolerance in the post-processing. So, the reported PSMs will be still with small parent mass tolerance.
This setting indeed increases searching time, but it also finds more PSMs with FDR well controlled compared to stringent parent mass tolerance.


---------------------------------------------------------
Xuan (Shawn) Guo, PhD

Assistant Professor
Dept of Computer Science and Engineering

University of North Texas

http://www.cse.unt.edu/~xuanguo/

(940) 565-2817

________________________________

**Comment by andrewjmc** [comment]
OK, thanks for the explanation!
